// <auto-generated />
namespace SurveyEducation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitDatabase3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitDatabase3));
        
        string IMigrationMetadata.Id
        {
            get { return "202204251522481_InitDatabase3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
